defaults:
  - override hydra/launcher: submitit_local

model:
  model: SimCLR
  backbone_model: resnet50
  projector: 2048-128
  temperature: 0.5

optim:
  epochs: 1000
  batch_size: 256
  lr: 1.5
  optimizer: LARS
  weight_decay: 1e-6

log:
  folder: "."
  wandb_project: "simclr_cifar10"

hardware:
  seed: 0
  float16: true
  gpu: 0
  world_size: 1
