# inspired from https://github.com/matthias-wright/cifar10-resnet

model:
  model: Supervised
  backbone_model: resnet9

optim:
  epochs: 75
  batch_size: 256
  lr: 0.001
  optimizer: Adam
  weight_decay: 0

log:
  folder: "./new_logs"
  project: "supervised_cifar10"

hardware:
  seed: 0
  float16: true
  gpu: 0
  world_size: 1
