data:
  data_dir: /projects/users/hvanasse/ssl-dev/stable-SSL/runs/data/CIFAR10
  dataset: CIFAR10
  num_classes: 10
  resolution: 32
hardware:
  float16: false
  gpu: 0
  port: null
  seed: null
  workers: 0
  world_size: 1
log:
  checkpoint_frequency: 10
  entity: null
  eval_each_epoch: true
  eval_only: false
  final_model_name: final_model
  folder: .
  load_from: ckpt
  log_level: 20
  project: null
  run_name: null
  save_final_model: false
model:
  autoclr_K: 10
  backbone_model: resnet18
  memory_format: channels_last
  model: SimCLR
  pretrained: false
  projector: 2048-128
  sync_batchnorm: false
  temperature: 0.15
  with_classifier: true
optim:
  batch_size: 256
  betas: null
  epochs: 1000
  grad_max_norm: null
  lr: 1.0
  max_steps: -1
  momentum: 0
  nesterov: false
  optimizer: LARS
  weight_decay: 1.0e-06
