# config.yaml
model:
  architecture: "resnet50"

training:
  folder: "./new_logs"
  add_version: true
  load_from: null
  log_level: 10  # logging.DEBUG
  seed: 123
  float16: true
  gpu: 1
  world_size: 2
  eval_only: false
  epochs: 25
  checkpoint_frequency: 5