# config.yaml
general:
  seed: 123
  eval_only: false
  epochs: 25
  
model:
  architecture: "resnet50"

log:
  folder: "./new_logs"
  add_version: false
  log_level: 10  # logging.DEBUG
  checkpoint_frequency: 5

hardware:
  float16: true
  gpu: 1
  world_size: 2