# config.yaml
model:
  architecture: "resnet50"

log:
  folder: "./new_logs"
  add_version: false
  load_from: null
  log_level: 10  # logging.DEBUG
  checkpoint_frequency: 5

general:
  seed: 123
  eval_only: false
  epochs: 25

hardware:
  float16: true
  gpu: 1
  world_size: 2