# config.yaml

data:
  data_dir : "./data"
  
optim:
  epochs: 1
  batch_size: 256
  
model:
  backbone_model: "resnet18"

log:
  folder: "./new_logs"
  eval_only: false
  checkpoint_frequency: 5

hardware:
  seed: 0
  float16: false
  gpu: 0
  world_size: 1