model:
  model: Supervised
  backbone_model: resnet18

optim:
  epochs: 100
  batch_size: 256
  lr: 0.001
  optimizer: Adam
  weight_decay: 0

log:
  folder: "./new_logs"
  wandb_project: "supervised_cifar10"

hardware:
  seed: 0
  float16: true
  gpu: 0
  world_size: 1
