# inspired from https://github.com/p3i0t/SimCLR-CIFAR10

model:
  name: SimCLR
  backbone_model: resnet18
  projector: 2048-128
  temperature: 0.5

optim:
  epochs: 1000
  batch_size: 512
  lr: 0.6
  optimizer: SGD
  weight_decay: 1e-6
  momentum: 0.9

log:
  folder: "./new_logs"
  project: "simclr_cifar10"

hardware:
  seed: 0
  float16: true
  gpu: 0
  world_size: 1
